# Generated by Django 3.2.4 on 2024-08-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'comunas',
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField()),
                ('m2_totales', models.FloatField()),
                ('cantidad_estacionamientos', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('tipo_inmueble', models.CharField(max_length=20)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'regiones',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_personal', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.CharField(max_length=255, unique=True)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuariosPropiedadesFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendahogar_aplicacion.propiedades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendahogar_aplicacion.usuarios')),
            ],
            options={
                'db_table': 'usuarios_propiedades_favoritas',
                'unique_together': {('usuario', 'propiedad')},
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='propiedades_favoritas',
            field=models.ManyToManyField(related_name='usuarios_favoritos', through='arriendahogar_aplicacion.UsuariosPropiedadesFavoritas', to='arriendahogar_aplicacion.Propiedades'),
        ),
        migrations.CreateModel(
            name='PropiedadesComunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendahogar_aplicacion.comunas')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendahogar_aplicacion.propiedades')),
            ],
            options={
                'db_table': 'propiedades_comunas',
                'unique_together': {('propiedad', 'comuna')},
            },
        ),
        migrations.AddField(
            model_name='propiedades',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_publicadas', to='arriendahogar_aplicacion.usuarios'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='comunas',
            field=models.ManyToManyField(related_name='propiedades', through='arriendahogar_aplicacion.PropiedadesComunas', to='arriendahogar_aplicacion.Comunas'),
        ),
        migrations.AddField(
            model_name='comunas',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='arriendahogar_aplicacion.regiones'),
        ),
        migrations.CreateModel(
            name='Arrendamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamientos', to='arriendahogar_aplicacion.usuarios')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamientos', to='arriendahogar_aplicacion.propiedades')),
            ],
            options={
                'db_table': 'arrendamientos',
            },
        ),
    ]
